export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODES = {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	NOT_FOUND: "NOT_FOUND",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	CONFLICT: "CONFLICT",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export const RATE_LIMITS = {
	AUTH: {
		WINDOW_MS: 15 * 60 * 1000, // 15 minutes
		MAX_REQUESTS: 5,
	},
	API: {
		WINDOW_MS: 15 * 60 * 1000, // 15 minutes
		MAX_REQUESTS: 100,
	},
	STRICT: {
		WINDOW_MS: 60 * 1000, // 1 minute
		MAX_REQUESTS: 10,
	},
} as const;

export const PAGINATION = {
	DEFAULT_LIMIT: 10,
	MAX_LIMIT: 100,
	DEFAULT_OFFSET: 0,
} as const;